"""
Campaign Results Exporter
==========================

Utilities for exporting and packaging campaign results in various formats.
"""

import os
import json
import zipfile
from datetime import datetime
from io import BytesIO
import base64


def create_campaign_summary_md(state: dict) -> str:
    """Generate a comprehensive markdown summary of the campaign"""
    
    product_info = state.get('product_info', 'N/A')
    campaign_goal = state.get('campaign_goal', 'N/A')
    target_audience = state.get('target_audience', 'N/A')
    iterations = state.get('iteration_count', 0)
    max_iterations = state.get('max_iterations', 0)
    threshold = state.get('performance_threshold', 0)
    status = state.get('campaign_status', 'unknown')
    
    files = state.get('files', {})
    todos = state.get('todos', [])
    
    # Count files by type
    strategy_files = len([f for f in files.keys() if 'strategy_report' in f])
    content_files = len([f for f in files.keys() if 'post_content' in f])
    analytics_files = len([f for f in files.keys() if 'analytics_report' in f])
    image_files = len([f for f in files.keys() if 'image_data' in f])
    chart_files = len([f for f in files.keys() if 'chart' in f])
    
    summary = f"""# Marketing Campaign Summary

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Status:** {status.upper()}

---

## Campaign Overview

### Product Information
{product_info}

### Campaign Goal
{campaign_goal}

### Target Audience
{target_audience}

---

## Campaign Execution

- **Iterations Completed:** {iterations} / {max_iterations}
- **Performance Threshold:** {threshold}%
- **Final Status:** {status.replace('_', ' ').title()}

---

## Deliverables Generated

| Category | Count |
|----------|-------|
| Strategy Reports | {strategy_files} |
| Content Pieces | {content_files} |
| Analytics Reports | {analytics_files} |
| Generated Images | {image_files} |
| Performance Charts | {chart_files} |
| **Total Files** | **{len(files)}** |

---

## Task Completion

Total Tasks: {len(todos)}

"""
    
    # Add todo status
    if todos:
        completed = len([t for t in todos if t.get('status') == 'completed'])
        in_progress = len([t for t in todos if t.get('status') == 'in_progress'])
        pending = len([t for t in todos if t.get('status') == 'pending'])
        
        summary += f"""- ✅ Completed: {completed}
- 🔄 In Progress: {in_progress}
- ⏳ Pending: {pending}

"""
    
    # Add performance summary if analytics available
    analytics_files_list = sorted([f for f in files.keys() if 'analytics_report' in f])
    if analytics_files_list:
        summary += "\n## Performance Summary\n\n"
        for analytics_file in analytics_files_list:
            content = files[analytics_file]
            # Try to extract performance score
            if "Performance Score:" in content:
                score_line = [l for l in content.split('\n') if 'Performance Score:' in l]
                if score_line:
                    summary += f"- {analytics_file}: {score_line[0].split(':')[1].strip()}\n"
    
    summary += "\n---\n\n## Files Generated\n\n"
    
    # List all files by iteration
    iterations_dict = {}
    other_files = []
    
    for filename in sorted(files.keys()):
        if '_v' in filename:
            try:
                iter_num = int(filename.split('_v')[1].split('.')[0])
                if iter_num not in iterations_dict:
                    iterations_dict[iter_num] = []
                iterations_dict[iter_num].append(filename)
            except:
                other_files.append(filename)
        else:
            other_files.append(filename)
    
    for iter_num in sorted(iterations_dict.keys()):
        summary += f"\n### Iteration {iter_num}\n\n"
        for filename in sorted(iterations_dict[iter_num]):
            summary += f"- `{filename}`\n"
    
    if other_files:
        summary += "\n### Other Files\n\n"
        for filename in sorted(other_files):
            summary += f"- `{filename}`\n"
    
    summary += "\n---\n\n*Generated by Marketing Campaign Multi-Agent System*\n"
    
    return summary


def create_campaign_json(state: dict) -> str:
    """Export campaign data as JSON"""
    
    export_data = {
        "export_date": datetime.now().isoformat(),
        "campaign_config": {
            "product_info": state.get('product_info', ''),
            "campaign_goal": state.get('campaign_goal', ''),
            "target_audience": state.get('target_audience', ''),
            "max_iterations": state.get('max_iterations', 0),
            "performance_threshold": state.get('performance_threshold', 0),
        },
        "execution": {
            "iteration_count": state.get('iteration_count', 0),
            "campaign_status": state.get('campaign_status', 'unknown'),
        },
        "todos": state.get('todos', []),
        "files": {
            "count": len(state.get('files', {})),
            "filenames": list(state.get('files', {}).keys())
        },
        "summary": {
            "strategy_reports": len([f for f in state.get('files', {}).keys() if 'strategy_report' in f]),
            "content_pieces": len([f for f in state.get('files', {}).keys() if 'post_content' in f]),
            "analytics_reports": len([f for f in state.get('files', {}).keys() if 'analytics_report' in f]),
            "images": len([f for f in state.get('files', {}).keys() if 'image_data' in f]),
        }
    }
    
    return json.dumps(export_data, indent=2)


def create_zip_archive(state: dict) -> BytesIO:
    """Create a ZIP archive with all campaign files"""
    
    zip_buffer = BytesIO()
    
    with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:
        
        # Add summary
        summary_md = create_campaign_summary_md(state)
        zip_file.writestr('CAMPAIGN_SUMMARY.md', summary_md)
        
        # Add JSON export
        json_data = create_campaign_json(state)
        zip_file.writestr('campaign_data.json', json_data)
        
        # Add all files
        files = state.get('files', {})
        
        # Organize by iteration
        for filename, content in files.items():
            # Skip error files
            if filename.startswith('URL_error'):
                continue
            
            # Determine folder
            if '_v' in filename:
                try:
                    iter_num = int(filename.split('_v')[1].split('.')[0])
                    folder = f"iteration_{iter_num}"
                except:
                    folder = "other"
            else:
                folder = "other"
            
            # Handle image data files
            if filename.endswith('_data.txt') or 'image_data' in filename:
                # Try to decode and save as PNG
                try:
                    lines = content.split('\n')
                    b64_data = None
                    for line in lines:
                        line = line.strip()
                        if len(line) > 1000:
                            b64_data = line
                            break
                    
                    if b64_data:
                        img_bytes = base64.b64decode(b64_data)
                        png_filename = filename.replace('_data.txt', '.png')
                        zip_file.writestr(f"{folder}/images/{png_filename}", img_bytes)
                except:
                    pass
                
                # Also save the base64 file
                zip_file.writestr(f"{folder}/{filename}", content)
            else:
                # Regular text file
                zip_file.writestr(f"{folder}/{filename}", content)
    
    zip_buffer.seek(0)
    return zip_buffer


def get_export_filename(product_name: str = "campaign") -> str:
    """Generate a timestamped export filename"""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_name = "".join(c for c in product_name if c.isalnum() or c in (' ', '-', '_')).rstrip()
    safe_name = safe_name.replace(' ', '_').lower()
    return f"{safe_name}_{timestamp}.zip"


def export_iteration_comparison(state: dict) -> str:
    """Export iteration comparison data as CSV"""
    
    files = state.get('files', {})
    analytics_files = sorted([f for f in files.keys() if 'analytics_report' in f])
    
    if not analytics_files:
        return "iteration,status\n"
    
    csv_lines = ["iteration,performance_score,status"]
    
    for analytics_file in analytics_files:
        try:
            iter_num = int(analytics_file.split('_v')[1].split('.')[0])
            content = files[analytics_file]
            
            # Extract performance score
            score = "N/A"
            if "Performance Score:" in content:
                score_line = [l for l in content.split('\n') if 'Performance Score:' in l]
                if score_line:
                    score = score_line[0].split(':')[1].strip().split('/')[0]
            
            status = "completed"
            csv_lines.append(f"{iter_num},{score},{status}")
        except:
            continue
    
    return "\n".join(csv_lines)


def create_html_report(state: dict) -> str:
    """Generate an HTML report of the campaign"""
    
    product_info = state.get('product_info', 'N/A')
    campaign_goal = state.get('campaign_goal', 'N/A')
    iterations = state.get('iteration_count', 0)
    max_iterations = state.get('max_iterations', 0)
    status = state.get('campaign_status', 'unknown')
    
    files = state.get('files', {})
    
    # Count files
    strategy_files = len([f for f in files.keys() if 'strategy_report' in f])
    content_files = len([f for f in files.keys() if 'post_content' in f])
    analytics_files = len([f for f in files.keys() if 'analytics_report' in f])
    image_files = len([f for f in files.keys() if 'image_data' in f])
    
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Campaign Report</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 30px;
        }}
        .card {{
            background: white;
            padding: 20px;
            border-radius: 10px;
            margin-bottom: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .metrics {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }}
        .metric {{
            text-align: center;
            padding: 20px;
            background: white;
            border-radius: 10px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .metric-value {{
            font-size: 2em;
            font-weight: bold;
            color: #667eea;
        }}
        .metric-label {{
            color: #666;
            margin-top: 5px;
        }}
        .status {{
            display: inline-block;
            padding: 5px 15px;
            border-radius: 20px;
            font-weight: 600;
        }}
        .status-completed {{ background: #d4edda; color: #155724; }}
        .status-running {{ background: #fff3cd; color: #856404; }}
        .status-failed {{ background: #f8d7da; color: #721c24; }}
        h1, h2, h3 {{ color: #333; }}
        .file-list {{ list-style: none; padding: 0; }}
        .file-list li {{
            padding: 10px;
            border-left: 4px solid #667eea;
            margin: 5px 0;
            background: #f8f9fa;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🚀 Marketing Campaign Report</h1>
        <p>Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
        <span class="status status-{status}">{status.upper()}</span>
    </div>
    
    <div class="metrics">
        <div class="metric">
            <div class="metric-value">{iterations}/{max_iterations}</div>
            <div class="metric-label">Iterations</div>
        </div>
        <div class="metric">
            <div class="metric-value">{len(files)}</div>
            <div class="metric-label">Files Generated</div>
        </div>
        <div class="metric">
            <div class="metric-value">{strategy_files}</div>
            <div class="metric-label">Strategies</div>
        </div>
        <div class="metric">
            <div class="metric-value">{content_files}</div>
            <div class="metric-label">Content Pieces</div>
        </div>
    </div>
    
    <div class="card">
        <h2>Product Information</h2>
        <p>{product_info.replace(chr(10), '<br>')}</p>
    </div>
    
    <div class="card">
        <h2>Campaign Goal</h2>
        <p>{campaign_goal}</p>
    </div>
    
    <div class="card">
        <h2>Deliverables</h2>
        <ul class="file-list">
            <li>✅ {strategy_files} Strategy Reports</li>
            <li>✅ {content_files} Content Pieces</li>
            <li>✅ {analytics_files} Analytics Reports</li>
            <li>✅ {image_files} Generated Images</li>
        </ul>
    </div>
    
    <div class="card">
        <h2>Files Generated</h2>
        <ul class="file-list">
"""
    
    for filename in sorted(files.keys()):
        if not filename.startswith('URL_error'):
            html += f"            <li>{filename}</li>\n"
    
    html += """        </ul>
    </div>
    
    <div class="card">
        <p style="text-align: center; color: #666;">
            <em>Generated by Marketing Campaign Multi-Agent System</em>
        </p>
    </div>
</body>
</html>"""
    
    return html
